### ISSUE TITLE
Uncaught runtime errors

### ISSUE THREAD

**Issue by Gazoon007** [cometchat-pro/cometchat-chat-sample-app-vue#59]
### Describe the problem

Edit message inside the thread

Showing error like this

```
ERROR
Maximum recursive updates exceeded in component <CometChatMessageComposer>. This means you have a reactive effect that is mutating its own dependencies and thus recursively triggering itself. Possible sources include component template, render function, updated hook or watcher source function.
    at handleError (webpack-internal:///./node_modules/webpack-dev-server/client/overlay.js:252:58)
    at eval (webpack-internal:///./node_modules/webpack-dev-server/client/overlay.js:275:7)
```
### What was the expected behavior?

No error, message edited successfully and reactively

### Reproduction

1. Open thread 
2. edit message in the thread that is exist already
3. close thread
4. open the same thread
5. edit message
6. error showed up 

https://github.com/user-attachments/assets/87782fc0-4e15-4755-b3ac-b72a796498eb

### Environment

node v16.20.2 (npm v8.19.4)
v4

**Comment by Gazoon007** [comment]
Closed this issue and I will create it in the UI kit instead since the problem is in the UI kit
